import turtle
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot()
turtle.forward(130)
turtle.dot
turtle.forward(130)
turtle.dot
turtle.forward(130)